project:
  type: website
  render:
    - index.qmd
    - pages/*.qmd  # Cette ligne inclura tous les fichiers .qmd dans le dossier "pages"

website:
  back-to-top-navigation: true
  page-navigation: true
  title: "Myte_project"
  site-url: https://bossdidiboss.github.io/myte_project/
  repo-url: https://github.com/BossdiDiboss/myte_project
  repo-actions: [source,issue]
  navbar:
    title: "Mayotte"
    background: darkgreen
    search: true
    items:
      - title: "Mamoudzou"
        url: mamoudzou.html
      - title: "Cavani"
        url: cavani.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
