project:
  type: website
  render:
    - index.qmd
    - webpage/mamoudzou/tp.qmd
    - webpage/cavani/tp.qmd

website:
  back-to-top-navigation: true
  page-navigation: true
  title: "Myte_project"
  site-url: https://bossdidiboss.github.io/myte_project/
  repo-url: https://github.com/BossdiDiboss/myte_project
  repo-actions: [source,issue]
  navbar:
    title: "Mayotte"
    background: darkgreen
    search: true
    left:
      - sidebar:commune
      - sidebar:quartier
  sidebar:
    - id: commune
      title: "Commune"
      collapse-level: 3
      contents:
          - webpage/mamoudzou/tp.qmd
          - webpage/dembeni/tp.qmd
    - id: quartier
      title: "Quartier"
      collapse-level: 3
      contents:
      - webpage/cavani/tp.qmd
      - webpage/mtsapere/tp.qmd
      - webpage/iloni/tp.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
